# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'TEACHHMe' do
pod "MagicalRecord"

end

target 'TEACHHMeTests' do

end

